/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sp.tads.view;

import br.sp.senac.tads.model.Vendedor;
import br.sp.tads.controller.VendedorController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrador
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_superior = new javax.swing.JPanel();
        lbl_fechar = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btn_acessar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_superior.setBackground(new java.awt.Color(0, 95, 72));
        pnl_superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_fechar.setBackground(new java.awt.Color(0, 95, 72));
        lbl_fechar.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        lbl_fechar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fechar.setText("X");
        lbl_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_fecharMouseClicked(evt);
            }
        });
        pnl_superior.add(lbl_fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jPanel1.add(pnl_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 60));

        txt_usuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(51, 51, 51));
        txt_usuario.setBorder(null);
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 250, -1));

        jSeparator1.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator1.setForeground(new java.awt.Color(40, 40, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 250, 10));

        jSeparator2.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator2.setForeground(new java.awt.Color(40, 40, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 250, 10));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setText("Senha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        btn_acessar.setBackground(new java.awt.Color(0, 95, 72));
        btn_acessar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_acessar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_acessarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_acessarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_acessarMouseExited(evt);
            }
        });
        btn_acessar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Acessar");
        btn_acessar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jPanel1.add(btn_acessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 100, 40));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setText("Usuário");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        txt_senha.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txt_senha.setBorder(null);
        jPanel1.add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 250, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_fecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_fecharMouseClicked

    private void btn_acessarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acessarMouseEntered
        setColor(btn_acessar);
    }//GEN-LAST:event_btn_acessarMouseEntered

    private void btn_acessarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acessarMouseExited
        resetColor(btn_acessar);
    }//GEN-LAST:event_btn_acessarMouseExited

    private void btn_acessarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acessarMouseClicked
        
        Vendedor vendBean = new Vendedor();
        VendedorController vendControl = new VendedorController();
        
        if (!txt_usuario.getText().equals("") && !txt_senha.getText().equals("")) {
            
            vendBean.setUsuario(txt_usuario.getText());
            vendBean.setSenha(txt_senha.getText());
            
            ArrayList<Vendedor> credenciais = vendControl.validaLoginCOntroller(vendBean);

            if (credenciais.size() > 0) {

                for (Object obj : credenciais) {

                    Vendedor bean = (Vendedor) obj;
                   
                    vendBean.setCodVendedor(bean.getCodVendedor());
                    vendBean.setNome(bean.getNome());

                }
                
                JOptionPane.showMessageDialog(null, "Bem vindo, " + txt_usuario.getText() + "!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                Home home = new Home();
                home.show();
                this.dispose();

            } else {
                
                JOptionPane.showMessageDialog(null, "Erro no login", "Erro", JOptionPane.ERROR_MESSAGE);
                
                txt_usuario.setText("");
                txt_senha.setText("");
                                
            }
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Preencha os campos usuário e senha", "ERRO", JOptionPane.ERROR_MESSAGE);
            
        }

    }//GEN-LAST:event_btn_acessarMouseClicked
    
    /** ALTERAR A COR DO OBJETO AO PASSAR O MOUSE*/
    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(40, 40, 40));        
    }
    
    /** VOLTAR PARA A COR PADRÃO DO OBJETO AO TIRAR O MOUSE DE CIMA */
    public void resetColor(JPanel panel){    
        panel.setBackground(new java.awt.Color(0, 95, 72));        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_acessar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_fechar;
    private javax.swing.JPanel pnl_superior;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
