/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sp.tads.view;

import br.sp.senac.tads.model.Vendedor;
import br.sp.tads.controller.VendedorController;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrador
 */
public class VendedorCRUD extends javax.swing.JFrame {
    
    VendedorController vendedorControl = new VendedorController();
    
    
    /**
     * Creates new form IndexVendedor
     */
    public VendedorCRUD() {
        initComponents();
    }
    
    public VendedorCRUD(String operacao){
        initComponents();
        lbl_operacao.setText(operacao);
        setIcon(this);
        
        if (operacao.equals("Vendedor")) {
            lbl_concluir.setText("Fechar");
            btn_cancelar.setVisible(false);
            desabilitarCampos();
        }
        
    }
    
    /** ALTERAR A COR DO OBJETO AO PASSAR O MOUSE*/
    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(40, 40, 40));        
    }
    
    /** VOLTAR PARA A COR PADRÃO DO OBJETO AO TIRAR O MOUSE DE CIMA */
    public void resetColor(JPanel panel){    
        panel.setBackground(new java.awt.Color(0, 95, 72));        
    }
    
    public void setIcon(JFrame frm) {
        frm.setIconImage(Toolkit.getDefaultToolkit().getImage("src/main/resources/imagens/castanha.png"));
    }
    
    public boolean verifiaCampos() {
        boolean vazio = false;

        if (txt_nome.getText().equals("")) {
            vazio =  true;
        }
        
        if (txt_email.getText().equals("")) {
            vazio =  true;
        }
        
        if (txt_data.getText().equals("")) {
            vazio =  true;
        }
        
        if (txt_cpf.getText().equals("")) {
            vazio =  true;
        }
        
        if (txt_contato1.getText().equals("")) {
            vazio =  true;
        }
        
        if (txt_contato2.getText().equals("")) {
            vazio =  true;
        }
        
        if (txt_usuario.getText().equals("")) {
            vazio =  true;
        }
        
        if (txt_data.getText().equals("")) {
            vazio =  true;
        }

        return vazio;

    }
    
    public void preencheCampos(Vendedor vendedorBean) {
                       
        ArrayList<Vendedor> listaVendedor = vendedorControl.consultarController(vendedorBean);

        int i = 0;

        for (Object obj : listaVendedor) {

            Vendedor venBean = (Vendedor) obj;
            
           txt_nome.setText(venBean.getNome());
           txt_data.setText(venBean.getDataNascimento());
           txt_cpf.setText(venBean.getCpf());
           txt_email.setText(venBean.getEmail());
           txt_contato1.setText(venBean.getContato1());
           txt_contato2.setText(venBean.getContato2());
           txt_usuario.setText(venBean.getUsuario());
           txt_senha.setText(venBean.getSenha());
            
           i++;

        }
                       
    }
    
    public void desabilitarCampos() {
        
        txt_nome.setEditable(false);
        txt_data.setEditable(false);
        txt_cpf.setEditable(false);
        txt_email.setEditable(false);
        txt_contato1.setEditable(false);
        txt_contato2.setEditable(false);
        txt_usuario.setEditable(false);
        txt_senha.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_fundo = new javax.swing.JPanel();
        pnl_lateral = new javax.swing.JPanel();
        pnl_botoesEstado = new javax.swing.JPanel();
        lbl_minimizar = new javax.swing.JLabel();
        lbl_fechar = new javax.swing.JLabel();
        lbl_operacao = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JPanel();
        lbl_usuarioSessao1 = new javax.swing.JLabel();
        btn_concluir = new javax.swing.JPanel();
        lbl_concluir = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txt_contato1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txt_contato2 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_senha = new javax.swing.JPasswordField();
        txt_data = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_fundo.setBackground(new java.awt.Color(255, 255, 255));
        pnl_fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_lateral.setBackground(new java.awt.Color(0, 95, 72));
        pnl_lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_botoesEstado.setBackground(new java.awt.Color(0, 95, 72));
        pnl_botoesEstado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_minimizar.setBackground(new java.awt.Color(0, 95, 72));
        lbl_minimizar.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        lbl_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_minimizar.setText("_");
        lbl_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizarMouseClicked(evt);
            }
        });
        pnl_botoesEstado.add(lbl_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, -1, 60));

        lbl_fechar.setBackground(new java.awt.Color(0, 95, 72));
        lbl_fechar.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        lbl_fechar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fechar.setText("X");
        lbl_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_fecharMouseClicked(evt);
            }
        });
        pnl_botoesEstado.add(lbl_fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        pnl_lateral.add(pnl_botoesEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 80, 50));

        lbl_operacao.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lbl_operacao.setForeground(new java.awt.Color(255, 255, 255));
        lbl_operacao.setText("Operação");
        pnl_lateral.add(lbl_operacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, -1));

        pnl_fundo.add(pnl_lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        btn_cancelar.setBackground(new java.awt.Color(0, 95, 72));
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseExited(evt);
            }
        });
        btn_cancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_usuarioSessao1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbl_usuarioSessao1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuarioSessao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_usuarioSessao1.setText("Cancelar");
        btn_cancelar.add(lbl_usuarioSessao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        pnl_fundo.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 90, 50));

        btn_concluir.setBackground(new java.awt.Color(0, 95, 72));
        btn_concluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_concluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_concluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_concluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_concluirMouseExited(evt);
            }
        });
        btn_concluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_concluir.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbl_concluir.setForeground(new java.awt.Color(255, 255, 255));
        lbl_concluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_concluir.setText("Concluir");
        btn_concluir.add(lbl_concluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        pnl_fundo.add(btn_concluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 90, 50));

        txt_nome.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txt_nome.setForeground(new java.awt.Color(51, 51, 51));
        txt_nome.setBorder(null);
        pnl_fundo.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 350, -1));

        jSeparator1.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator1.setForeground(new java.awt.Color(40, 40, 40));
        pnl_fundo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 350, 10));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setText("Nome");
        pnl_fundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator3.setForeground(new java.awt.Color(40, 40, 40));
        pnl_fundo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 160, 10));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setText("CPF");
        pnl_fundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator4.setForeground(new java.awt.Color(40, 40, 40));
        pnl_fundo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 350, 10));

        txt_email.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(51, 51, 51));
        txt_email.setBorder(null);
        pnl_fundo.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 350, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setText("E-mail");
        pnl_fundo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator5.setForeground(new java.awt.Color(40, 40, 40));
        pnl_fundo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 160, 10));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setText("Data de nascimento");
        pnl_fundo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txt_contato1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txt_contato1.setForeground(new java.awt.Color(51, 51, 51));
        txt_contato1.setBorder(null);
        pnl_fundo.add(txt_contato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 160, -1));

        jSeparator6.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator6.setForeground(new java.awt.Color(40, 40, 40));
        pnl_fundo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 160, 10));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("Contato 1");
        pnl_fundo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        txt_contato2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txt_contato2.setForeground(new java.awt.Color(51, 51, 51));
        txt_contato2.setBorder(null);
        pnl_fundo.add(txt_contato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 160, -1));

        jSeparator7.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator7.setForeground(new java.awt.Color(40, 40, 40));
        pnl_fundo.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 160, 10));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setText("Contato 2");
        pnl_fundo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setText("Usuário");
        pnl_fundo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        txt_usuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(51, 51, 51));
        txt_usuario.setBorder(null);
        pnl_fundo.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 170, -1));

        jSeparator8.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator8.setForeground(new java.awt.Color(40, 40, 40));
        pnl_fundo.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 170, 10));

        jSeparator9.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator9.setForeground(new java.awt.Color(40, 40, 40));
        pnl_fundo.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 170, 10));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setText("Senha");
        pnl_fundo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        txt_cpf.setBorder(null);
        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pnl_fundo.add(txt_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 160, -1));

        txt_senha.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txt_senha.setBorder(null);
        pnl_fundo.add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 170, -1));

        txt_data.setBorder(null);
        try {
            txt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_data.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pnl_fundo.add(txt_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 160, -1));

        getContentPane().add(pnl_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseEntered
        setColor(btn_cancelar);
    }//GEN-LAST:event_btn_cancelarMouseEntered

    private void btn_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseExited
        resetColor(btn_cancelar);
    }//GEN-LAST:event_btn_cancelarMouseExited

    private void lbl_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizarMouseClicked
        this.setState(1);
    }//GEN-LAST:event_lbl_minimizarMouseClicked

    private void lbl_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_fecharMouseClicked
        Home home = new Home();
        home.show();
        this.dispose();
    }//GEN-LAST:event_lbl_fecharMouseClicked

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
        VendedorArea home = new VendedorArea();
        home.show();
        this.dispose();
    }//GEN-LAST:event_btn_cancelarMouseClicked

    private void btn_concluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_concluirMouseClicked
        
        Vendedor vendBean = new Vendedor();
        
        if (verifiaCampos()) {
            
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "ERRO", JOptionPane.ERROR_MESSAGE);
            
        } else {
            
            vendBean.setNome(txt_nome.getText());
            vendBean.setEmail(txt_email.getText());
            vendBean.setDataNascimento(txt_data.getText());
            vendBean.setCpf(txt_cpf.getText());
            vendBean.setContato1(txt_contato1.getText());
            vendBean.setContato2(txt_contato2.getText());
            vendBean.setUsuario(txt_usuario.getText());
            vendBean.setSenha(txt_senha.getText());
            
            
            if (lbl_operacao.getText().equals("Adicionar Vendedor")) {

                boolean status = vendedorControl.cadastrarController(vendBean);

                if (status) {

                    JOptionPane.showMessageDialog(null, "Vendedor cadastrado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);

                    VendedorArea home = new VendedorArea();
                    home.show();
                    this.dispose();

                } else {

                    JOptionPane.showMessageDialog(null, "Vendedor não cadastrado", "ERRO", JOptionPane.ERROR_MESSAGE);

                    VendedorArea home = new VendedorArea();
                    home.show();
                    this.dispose();

                }
                
            } else if (lbl_operacao.getText().equals("Editar Vendedor")) {
                
                boolean status = vendedorControl.editarController(vendBean);
                
                if (status) {

                    JOptionPane.showMessageDialog(null, "Vendedor editado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);

                    VendedorArea home = new VendedorArea();
                    home.show();
                    this.dispose();

                } else {

                    JOptionPane.showMessageDialog(null, "Vendedor não editado", "ERRO", JOptionPane.ERROR_MESSAGE);

                    VendedorArea home = new VendedorArea();
                    home.show();
                    this.dispose();

                }
                
            } else {
                
                VendedorArea home = new VendedorArea();
                home.show();
                this.dispose();
                
                
            }
            
        }

    }//GEN-LAST:event_btn_concluirMouseClicked

    private void btn_concluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_concluirMouseEntered
        setColor(btn_concluir);
    }//GEN-LAST:event_btn_concluirMouseEntered

    private void btn_concluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_concluirMouseExited
        resetColor(btn_concluir);
    }//GEN-LAST:event_btn_concluirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendedorCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendedorCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendedorCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendedorCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendedorCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_cancelar;
    private javax.swing.JPanel btn_concluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl_concluir;
    private javax.swing.JLabel lbl_fechar;
    private javax.swing.JLabel lbl_minimizar;
    private javax.swing.JLabel lbl_operacao;
    private javax.swing.JLabel lbl_usuarioSessao1;
    private javax.swing.JPanel pnl_botoesEstado;
    private javax.swing.JPanel pnl_fundo;
    private javax.swing.JPanel pnl_lateral;
    private javax.swing.JTextField txt_contato1;
    private javax.swing.JTextField txt_contato2;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
